compile: count 

count: count.o
	g++ count.o -o count

count.o: count.cc
	g++ -c count.cc

doc/index.html: Doxyfile src/*.cpp include/*.hpp
    doxygen Doxyfile

.PHONY: doc
	doc: doc/index.html ;

clean:
	rm -rf *o count

cleanDoc:
		rm doc/* -rf